apiVersion: v1
kind: Service
metadata:
  name: customer-backend-service
  namespace: banking
spec:
  selector:
    app: customer-backend-app
  ports:
  - protocol: TCP
    port: 9997
    targetPort: 9997