apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-configmap
  namespace: banking
data:
  containerPort: "9997"
  swaggerPath: "/customer/actuator"
  containerBasePath: "/api/v1"
  mysqlDbHost: customer-mysql-service
  mysqlDbName: "customer-db"
  mysqlDbPort: "3306"
  dbConnectionTimeOut: "100000"
  dbIdleTimeOut: "600000"
  dbMaxLifeTimeOut: "1800000"
  redisDbHost: customer-redis-service
  redisDbPort: "6379"
  logRootLevel: "INFO"
  logAppLevel: "DEBUG"
  cbFailureThreshold: "25"
  cbFailureMinNoCall: "10"
  cbFailurePermittedNoCallsInHalfOpenState: "10"
  cbFailureSlidingWindow: "55"
  cbFailureWaitDurationInOpenState: "10s"
  defaultCacheTtl: "5"
  appCacheTtl: "10"