server:
  port: 9997
  shutdown: graceful
  servlet:
    contextPath: /api/v1
  ######### SPRING BASED PATH ################
management:
  endpoints:
    web:
      base-path: /customer/actuator
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
spring:
  application:
    name: customer-service
  threads:
    virtual:
      enabled: true #Spring 3.2 feature
  ######## JPA ########
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  ######## DB PROPERTIES ########
  datasource:
    url: jdbc:mysql://localhost:3306/payment-db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: social_user
    password: mysql2024
    hikari.connectionTimeout: 100000
    hikari.idleTimeout: 600000
    hikari.maxLifetime: 1800000
  ######## DB MIGRATION ########
  flyway:
    url: jdbc:mysql://localhost:3306/payment-db?createDatabaseIfNotExist=true
    user: social_user
    password: mysql2024
    baseline:
      version: 1
    locations: classpath:db/migration
    enabled: true
  ######## REDIS CACHE #######
  redis:
    host: 127.0.0.1
    port: 6379
  ######## SPRING DOC ########
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/swagger-ui.html
  show-actuator: true
  ######## LOGGING ########
logging:
  level:
    root: INFO
    com.microservice.*: DEBUG
  ######## CIRCRUIT BREAKR ########
resilience4j:
  circuitbreaker:
    instances:
      payment-service:
        failureRateThreshold: 25
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 10
        slidingWindowSize: 55
        waitDurationInOpenState: 10s
        slidingWindowType: COUNT_BASED
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
        ignoreExceptions:
          - com.microservice.customer.exception.DuplicateException
          - com.microservice.customer.exception.NotFoundException
          - com.microservice.customer.exception.GenericException
  ######### CACHE CONFIGURATION #############
cache:
  default:
    time-to-live: 5 #minutes
  payment:
    time-to-live: 10 # minutes